<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $properties = [
            ['id' => 1, 'property_name' => 'クレドハウス新宿', 'route1' => '都営大江戸線', 'station1' => '東新宿', 'station_walk1' => 5, 'city' => '新宿区', 'station2' => '', 'station_walk2' => null, 'lounge' => '共用TV１台,ソファー,テーブル', 'kitchen' => '各部屋付き', 'shawer' => '各部屋付き', 'bath' => 'なし', 'is_bath_free' => true, 'laundry' => '1台(200円)', 'is_laundry_free' => false, 'dryer' => '1台(100円)', 'is_dryer_free' => false, 'toilet' => '各部屋付き', 'parking' => '自転車,バイク', 'is_parking' => true, 'is_parking_free' => true, 'internet' => '無線LAN', 'internet_memo' => '',  'is_internet_free' => true, 'total_rooms' => 14,  'area_info1' => 'コンビニ', 'area_info_walk1' => 2, 'area_info2' => 'スーパー', 'area_info_walk2' => 5, 'area_info3' => '公園', 'area_info_walk3' => 10, 'clean_style' => '清掃業者', 'clean_frequency' => '週3回程度', 'rule1' => '全館禁煙', 'rule2' => '', 'introduce' => '新宿まで徒歩圏内！！閑静な住宅街に位置し、周辺には銭湯や大型コインランドリーがあり、とても生活に便利です。
            カギですが、玄関はリモコンキー、各室はカードキー対応となっており防犯面を重視したゲストハウスとなっております。
            また、ゲストハウスには、珍しい各室内に洋式トイレ、シャワーが完備されており、共用部には、ソファー、テレビ、無線LAN、冷蔵庫、レンジ、コインランドリーがあります。', 'area_id' => 1, 'is_private_room' => true, 'is_dormitory' => false, 'is_women_only' => false, 'is_vacancy' => true, 'is_foreigner' => false, 'feature1' => '屋上、有り', 'feature2' => '屋上、オートロック機能付き', 'campaign' => '初期費用半額キャンペーン中！', 'main_image' => '物件1.jpg'],
            ['id' => 2, 'property_name' => 'FRESH shareJINGUMAE', 'route1' => 'JR山手線', 'station1' => '渋谷', 'station_walk1' => 10, 'station2' => '表参道', 'station_walk2' => 12,  'city' => '渋谷区', 'lounge' => '共用TV 1台,DVD付', 'kitchen' => '共用キッチン 1箇所', 'shawer' => '3室', 'bath' => 'バスルーム 1室＊¥200／20分', 'is_bath_free' => false, 'laundry' => '2台＊¥200', 'is_laundry_free' => false, 'dryer' => '1台＊￥100／20分', 'is_dryer_free' => false, 'toilet' => '洋式6室', 'parking' => '', 'is_parking' => false,  'is_parking_free' => true, 'internet' => '回線 光ファイバー （無料）', 'internet_memo' => '＊無線LAN、有線LAN（全室）有り。', 'is_internet_free' => true, 'total_rooms' => 22, 'area_info1' => '代々木公園', 'area_info_walk1' => 20, 'area_info2' => 'マクドナルド', 'area_info_walk2' => 7, 'area_info3' => 'ファミリーマート', 'area_info_walk3' => 5, 'clean_style' => '清掃業者', 'clean_frequency' => '週3回程度', 'rule1' => '喫煙所のみ喫煙可', 'rule2' => '友人の宿泊は要事前連絡。女性のみ宿泊可で、1泊¥2000。', 'introduce' => 'FRESH shareJINGUMAEは、2013年3月誕生しました。渋谷・原宿・表参道にほど近い、「暮らし」と「アクティブ」両方が叶う都内でも随一の好立地。ヘルスコンシャスかつアクティブなライフスタイルを送りたい女性たちのためのシェアハウスです。また、この女性目線のシェアハウスのプロデューサーとして、“走る女性のパワーで毎日を豊かに”をコンセプトに活動するメディア、ファッション、ビューティー業界の女性ランナー集団「RUN GIRL」が参画、屋上ヨガが楽しめる開放的な屋上テラス、広々としたキッチン、バスタブ付の浴室、大きめのシューズボックスなど、女性目線の嬉しい設備を充実させ、暮らしやすさと居心地のよさをとことん追求しました。入居者にはRUN GIRLプロデュースの“ラン＆フィットネス”イベント等も開催する予定も計画中です。新築の新しいコンセプト型シェアハウスFRESH shareJINGUMAEで新たな生活をスタートさせてみませんか？', 'area_id' => 1, 'is_private_room' => true, 'is_dormitory' => false, 'is_women_only' => false, 'is_vacancy' => true, 'is_foreigner' => true, 'feature1' => '屋上、ホームセキュリティ、防犯カメラ有り', 'feature2' => '屋上、オートロック機能付き', 'main_image' => '物件2.jpg', 'campaign' => ''],
            ['id' => 3, 'property_name' => 'CRAFT PACK 中野', 'route1' => 'JR中央線', 'station1' => '中野駅', 'station_walk1' => 10, 'station2' => '', 'station_walk2' => null, 'city' => '中野区', 'lounge' => '共用TV 1台', 'kitchen' => '', 'shawer' => '1室(男女兼用)', 'bath' => '', 'is_bath_free' => true, 'laundry' => '3台', 'is_laundry_free' => true, 'dryer' => '2台', 'is_dryer_free' => true, 'toilet' => '洋式1室（男女兼用）', 'parking' => '6台', 'is_parking' => true, 'is_parking_free' => true, 'internet' => '回線 光ファイバー', 'internet_memo' => '', 'is_internet_free' => true, 'total_rooms' => 13, 'area_info1' => '中野中央図書', 'area_info_walk1' => 4, 'area_info2' => 'スポーツクラブ', 'area_info_walk2' => 10, 'area_info3' => '紅葉山公園', 'area_info_walk3' => 5, 'clean_style' => '清掃業者', 'clean_frequency' => '週1回程度', 'rule1' => '喫煙は喫煙所のみ（建物内禁煙）', 'rule2' => '友人の宿泊は要事前連絡', 'introduce' => '街中の路地のような集合住宅、クリエイター、個人シャワートイレ完備、プライバシー、個人個人のスタイル、サブカルチャー、SOHO、友人客人招待可.etc...住んでる人みんなで集まってワイワイするようなリビングはありませんが、（シアター兼打ち合わせルームがある共用棟有り）路地で出会って立話、仲良く慣れば自分スタイルのお部屋に招待なんて形の関わり方ができるくらいの広いお部屋です。時には中野の沢山の飲み屋街などで交流を深めるのも可能な立地です。自分なりのスタイルで住んでいただける物件で皆様の時間と空間を共有してよりよい思い出を作っていただけたらと思います。', 'area_id' => 2, 'is_private_room' => true, 'is_dormitory' => false, 'is_women_only' => false, 'is_vacancy' => true, 'is_foreigner' => true, 'feature1' => 'ハンモックのあるアウトドアリビング', 'feature2' => '庭、ベランダ付き', 'main_image' => '物件3.jpg', 'campaign' => ''],
            ['id' => 4, 'property_name' => 'GIGI 自由が丘', 'route1' => '東急東横線', 'station1' => '自由が丘', 'station_walk1' => 10, 'station2' => '', 'station_walk2' => null, 'city' => '世田谷区', 'lounge' => '共用TV 1', 'kitchen' => '共用キッチン 1箇所', 'shawer' => '1室', 'bath' => '1室', 'is_bath_free' => true, 'laundry' => '1台', 'is_laundry_free' => true, 'dryer' => '', 'is_dryer_free' => true, 'toilet' => '洋式2室（男女兼用）', 'parking' => '有り', 'is_parking' => true, 'is_parking_free' => true, 'internet' => '光ファイバー', 'internet_memo' => '有線LAN（全室、リビング）有り', 'is_internet_free' => true, 'total_rooms' => 6, 'area_info1' => 'ファミリーマート', 'area_info_walk1' => 3, 'area_info2' => '大丸ピーコック', 'area_info_walk2' => 9, 'area_info3' => '図書館', 'area_info_walk3' => 10, 'clean_style' => '住人当番', 'clean_frequency' => '週1回程度', 'rule1' => '館内禁煙', 'rule2' => '友人の宿泊は要事前連絡', 'introduce' => '風の吹く長い坂の入口にある白い一軒家。そこにはゆったりとした自由で豊かな時間たち。 自由で心を満たして、季節の中をくぐりぬけて、何かにかわっていく生活たち。お洒落なインテリアショップのある通りを抜け、閑静な住宅街の中にあります。駅までの道には、大型スーパー、コンビニ、素敵な飲食店が揃っています。', 'area_id' => 3, 'is_private_room' => true, 'is_dormitory' => false, 'is_women_only' => false, 'is_vacancy' => true, 'is_foreigner' => true, 'feature1' => '洗濯機は乾燥機能付き', 'feature2' => '屋上、オートロック機能付き',  'main_image' => '物件1.jpg', 'campaign' => ''],
            ['id' => 5, 'property_name' => 'コレントハウス 馬込', 'route1' => '都営浅草線', 'station1' => '馬込駅', 'station_walk1' => 4, 'station2' => '大森', 'station_walk2' => 20, 'city' => '大田区', 'lounge' => '共用TV 1台', 'kitchen' => '共用キッチン 1箇所 ＊シンク等2セットずつ。', 'shawer' => '1室', 'bath' => '2室', 'is_bath_free' => true, 'laundry' => '3台', 'is_laundry_free' => true, 'dryer' => 'なし', 'is_dryer_free' => true, 'toilet' => '洋式3室', 'parking' => '', 'is_parking' => false,  'is_parking_free' => true, 'internet' => '光ファイバー ', 'internet_memo' => '無線LAN有り', 'is_internet_free' => true, 'total_rooms' => 15, 'area_info1' => '図書館', 'area_info_walk1' => 1, 'area_info2' => 'スーパー', 'area_info_walk2' => 3, 'area_info3' => 'ドラッグストア', 'area_info_walk3' => 3, 'clean_style' => '清掃業者、住人当番', 'clean_frequency' => '週1回程度', 'rule1' => '敷地内禁煙', 'rule2' => '友人の宿泊は要事前連絡', 'introduce' => '都営地下鉄浅草線「馬込」駅徒歩4分。「五反田」まで5分、新橋まで16分、と都内で働く女性に便利な女性専用シェアハウス「コレントハウス 馬込」がNEW OPEN！！「ナチュラル」をテーマにした内装で家に帰るとほっと一息、落ち着ける空間が広がります。15名のハウスは家に帰ると誰かの楽しげな話し声が聞こえてきて、毎日がプチ女子会で恋愛トークなどに花開き、「帰ると誰かがいてくれる、一人じゃない安心感」があります。共用玄関はカードキー、個室は個別ナンバーキーで安心セキュリティ。個室は全室6帖以上＋収納付きで南向きの窓がほとんどなので日当たり抜群です。周辺は馬込図書館が近く、読書家さんには嬉しい環境。駅前に大型ホームセンターがあり、1Fはスーパーになっているので日々の生活には困りません。小学校が近くにあり治安は都内とは思えない程良好。立ち話で地元のおばあちゃんとうっかり話しこんでしまうほどの和みエリアです。シェアハウスが住まい方の選択肢の一つとして定着してきた今だからこそ選んで欲しい「女性専用シェアハウス」。社員一同お待ちしております。', 'area_id' => 3, 'is_private_room' => true, 'is_dormitory' => false, 'is_women_only' => true, 'is_vacancy' => true, 'is_foreigner' => true, 'feature1' => '屋上有り', 'feature2' => '屋上、オートロック機能付き', 'main_image' => '物件2.jpg', 'campaign' => ''],
            ['id' => 6, 'property_name' => '赤羽 coromo', 'route1' => '宇都宮線', 'station1' => '赤羽駅', 'station_walk1' => 12, 'station2' => '', 'station_walk2' => null, 'city' => '北区', 'lounge' => '共用TV 1台', 'kitchen' => '共用キッチン 1箇所', 'shawer' => '1室', 'bath' => '1室', 'is_bath_free' => true, 'laundry' => '2台', 'is_laundry_free' => true, 'dryer' => false, 'is_dryer_free' => true, 'toilet' => '2室', 'parking' => '3台', 'is_parking' => true, 'is_parking_free' => true, 'internet' => '光ファイバー', 'internet_memo' => '', 'is_internet_free' => true, 'total_rooms' => 6, 'area_info1' => 'ファミリーマート', 'area_info_walk1' => 4, 'area_info2' => 'ドラッグストア', 'area_info_walk2' => 9, 'area_info3' => 'スーパー', 'area_info_walk3' => 3, 'clean_style' => '清掃業者', 'clean_frequency' => '週1回程度', 'rule1' => '喫煙所のみ喫煙可', 'rule2' => '友人の宿泊は不可', 'introduce' => '【日差しの差し込むリビングで朝食を楽しもう】急速にお洒落で便利に発展しながら、下町のお店も見え隠れする、埼玉、東京、横浜を往き来するターミナル駅「赤羽」に、エッジの効いた女性専用シェアが2017年3月にOPENしました。「お帰り」と玄関を開ける前に迎えてくれる「赤羽 coromo」の象徴でもある大きく立派な松の樹は表情も暖かく、頼もしく、美しい。空間コンシェルジュは今回のプロジェクトを進めるうえで、この松の樹を見て「天女の羽衣」の逸話が頭に浮かび、大切にコンセプトを温めてきました。美しい女性と松。切なくも綺麗で、不思議な出来事。本当にあったら素敵ですよね。そんな夢を描きながら暮らす女性、レースやシフォンのしなやかさ、情緒ある雰囲気。空間はそんなテイストで纏まっています。「赤羽 coromo」（hane coromo）のネーミングもそんな想いからきております。今回のコンセプトは、女性のしなやかさと、エキゾチックな雰囲気を蝶々の羽のようなイメージだと捉えております。本建物は、オーナーさまのご親族が大切に暮らされた後、今回の女性専用シェアハウスへと蘇り、節々に、元々の名残りの壁や階段などが温かく、しかしながら設備は新たで、快適に暮らせます。リビングや個室の窓から、松の樹や季節の植栽が臨めるのも、これまた味わい。そして何よりも気分が弾む異国情緒あるタイル貼りの造作キッチンで料理をすると、思わず鼻歌まで出てきてしまいそうなのです。Rシェア（Rバンクのシェアハウス）にご入居したら、料理の腕前も上がり、女子力UPして念願のゼクシィを買って、卒業します！ってお話もちらほら（微笑）。公園が近隣にあり、駅や駅からの途中にもスーパーやお花屋さん、パン屋さんもあり、ゆったりと、便利に、まったりと暮らしたい方へ「赤羽 coromo」はお勧めです。そして、勿論、女性専用シェアだからこそ、安心安全をきっちり考慮して警備保障会社、複製のできないカード鍵を採用。女性による清掃サービス、無線ですぐに使えるインターネット使い放題と、充実した設備は、まさに自分らしく働く素敵な女性にピッタリです。自信をもってお勧めできる空間が実現できました。', 'area_id' => 4, 'is_private_room' => true, 'is_dormitory' => false, 'is_women_only' => true, 'is_vacancy' => true, 'is_foreigner' => true, 'feature1' => '洗濯機は2台ともに簡易乾燥機能付き', 'feature2' => 'ホームセキュリティ付き', 'main_image' => '物件3.jpg', 'campaign' => ''],
            ['id' => 7, 'property_name' => 'FRAME house 浅草', 'route1' => '都営浅草線', 'station1' => '浅草駅', 'station_walk1' => 2, 'station2' => '蔵前', 'station_walk2' => 23, 'city' => '台東区', 'lounge' => '共用TV 1台。HDD録画、ブルーレイ付き。', 'kitchen' => '共用キッチン 1箇所', 'shawer' => '4室', 'bath' => '', 'is_bath_free' => true, 'laundry' => '4台', 'is_laundry_free' => true, 'dryer' => '', 'is_dryer_free' => true, 'toilet' => '3室', 'parking' => '', 'is_parking' => false,  'is_parking_free' => true, 'internet' => '光ファイバー ', 'internet_memo' => '', 'is_internet_free' => true, 'total_rooms' => 15, 'area_info1' => '浅草寺', 'area_info_walk1' => 2, 'area_info2' => 'スーパー', 'area_info_walk2' => 2, 'area_info3' => 'コンビニ', 'area_info_walk3' => 5, 'clean_style' => '清掃業者 ', 'clean_frequency' => '週1回程度', 'rule1' => '館内禁煙', 'rule2' => '友人の宿泊は要事前連絡', 'introduce' => '浅草の一等地に建つ『FRAME house 浅草』は、暮らしの品質を追求したシェアハウスです。キッチンと一体となった無垢材ダイニングテーブルを囲んで談笑したり、間接照明がほわりと灯るリビングでソファに転がって特大スクリーンを楽しんだり。開放的な空間がゆとりを与え、細部までしっかりとデザインされた共用空間が、暮らしの充足感を満たしてくれます。ウッドデッキと芝を敷いた屋上からの眺めは、ライトアップされた浅草寺やスカイツリーが一望でき、隅田川の花火も特等席となります。また、住宅設計の経験を活かし、防音ドア・防音壁・大開口が全室完備。住み心地はお墨付きです。住宅周辺は仲見世通り・伝法院通り・ホッピー通りに囲まれ、一年中活気にあふれています。飲み屋・飲食店も多いので、お酒が飲みたくなった時も困りません。国内随一のカルチャーの街・浅草と、ミニマムデザインのモダンライフの組み合わせが織りなすシェアライフ。シェアハウス初心者も常連もぜひ一度足を運んでみてください。', 'area_id' => 5, 'is_private_room' => true, 'is_dormitory' => false, 'is_women_only' => true, 'is_vacancy' => true, 'is_foreigner' => true, 'feature1' => '洗濯機は乾燥機能付き', 'feature2' => '屋上、オートロック機能付き', 'main_image' => '物件1.jpg', 'campaign' => '']
        ];
        DB::table('properties')->insert($properties);
    }
}
